<?php
/**
 * Content Builder - Creates pages with wp_insert_post using patterns
 *
 * @package PressPilot_Factory
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class PressPilot_Factory_Content_Builder {

    private $pattern_loader;

    public function __construct( PressPilot_Factory_Pattern_Loader $pattern_loader ) {
        $this->pattern_loader = $pattern_loader;
    }

    /**
     * Create a page with patterns
     */
    public function create_page( $title, $slug, $patterns, $params ) {
        // Build page content from patterns
        $content = $this->build_content( $patterns, $params );

        // Prepare post data
        $post_data = [
            'post_title'   => $title,
            'post_name'    => $slug,
            'post_content' => $content,
            'post_status'  => 'publish',
            'post_type'    => 'page',
            'post_author'  => get_current_user_id() ?: 1,
        ];

        // Check if page exists
        $existing = get_page_by_path( $slug );
        if ( $existing ) {
            $post_data['ID'] = $existing->ID;
            $page_id = wp_update_post( $post_data );
        } else {
            $page_id = wp_insert_post( $post_data );
        }

        if ( is_wp_error( $page_id ) ) {
            return false;
        }

        // Mark as generated by PressPilot
        update_post_meta( $page_id, '_presspilot_generated', true );
        update_post_meta( $page_id, '_presspilot_generation_time', current_time( 'mysql' ) );
        update_post_meta( $page_id, '_presspilot_patterns', $patterns );

        return $page_id;
    }

    /**
     * Build content from patterns
     */
    private function build_content( $patterns, $params ) {
        $content_parts = [];

        foreach ( $patterns as $pattern_name ) {
            $pattern_content = $this->pattern_loader->load_and_render( $pattern_name, $params );
            if ( $pattern_content ) {
                $content_parts[] = $pattern_content;
            }
        }

        return implode( "\n\n", $content_parts );
    }

    /**
     * Create WooCommerce pages if needed
     */
    public function create_woocommerce_pages( $params ) {
        if ( ! class_exists( 'WooCommerce' ) ) {
            return [];
        }

        $pages = [];

        // Shop page (uses WooCommerce shortcode)
        $shop_content = $this->get_shop_content( $params );
        $shop_id = $this->create_page( 'Shop', 'shop', [], $params );
        if ( $shop_id ) {
            wp_update_post([
                'ID'           => $shop_id,
                'post_content' => $shop_content,
            ]);
            update_option( 'woocommerce_shop_page_id', $shop_id );
            $pages['shop'] = $shop_id;
        }

        // Cart page
        $cart_id = $this->create_page( 'Cart', 'cart', [], $params );
        if ( $cart_id ) {
            wp_update_post([
                'ID'           => $cart_id,
                'post_content' => '<!-- wp:woocommerce/cart /-->',
            ]);
            update_option( 'woocommerce_cart_page_id', $cart_id );
            $pages['cart'] = $cart_id;
        }

        // Checkout page
        $checkout_id = $this->create_page( 'Checkout', 'checkout', [], $params );
        if ( $checkout_id ) {
            wp_update_post([
                'ID'           => $checkout_id,
                'post_content' => '<!-- wp:woocommerce/checkout /-->',
            ]);
            update_option( 'woocommerce_checkout_page_id', $checkout_id );
            $pages['checkout'] = $checkout_id;
        }

        // My Account page
        $account_id = $this->create_page( 'My Account', 'my-account', [], $params );
        if ( $account_id ) {
            wp_update_post([
                'ID'           => $account_id,
                'post_content' => '<!-- wp:woocommerce/my-account /-->',
            ]);
            update_option( 'woocommerce_myaccount_page_id', $account_id );
            $pages['my-account'] = $account_id;
        }

        return $pages;
    }

    /**
     * Get shop page content
     */
    private function get_shop_content( $params ) {
        $headline = $params['page_content']['headline'] ?? 'Our Products';
        $subheadline = $params['page_content']['subheadline'] ?? 'Browse our selection of quality products.';

        return '<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)">
<!-- wp:heading {"textAlign":"center","level":1} -->
<h1 class="wp-block-heading has-text-align-center">' . esc_html( $headline ) . '</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">' . esc_html( $subheadline ) . '</p>
<!-- /wp:paragraph -->

<!-- wp:woocommerce/all-products {"columns":3,"rows":3,"alignButtons":false,"contentVisibility":{"orderBy":true},"orderby":"date","layoutConfig":[["woocommerce/product-image",{"imageSizing":"thumbnail"}],["woocommerce/product-title"],["woocommerce/product-price"],["woocommerce/product-rating"],["woocommerce/product-button"]]} -->
<div class="wp-block-woocommerce-all-products wc-block-all-products" data-attributes="{&quot;columns&quot;:3,&quot;rows&quot;:3,&quot;alignButtons&quot;:false,&quot;contentVisibility&quot;:{&quot;orderBy&quot;:true},&quot;orderby&quot;:&quot;date&quot;,&quot;layoutConfig&quot;:[[&quot;woocommerce/product-image&quot;,{&quot;imageSizing&quot;:&quot;thumbnail&quot;}],[&quot;woocommerce/product-title&quot;],[&quot;woocommerce/product-price&quot;],[&quot;woocommerce/product-rating&quot;],[&quot;woocommerce/product-button&quot;]]}"></div>
<!-- /wp:woocommerce/all-products -->
</div>
<!-- /wp:group -->';
    }

    /**
     * Create restaurant menu page
     */
    public function create_menu_page( $params ) {
        $menu_items = $params['page_content']['items'] ?? [
            [ 'name' => 'Signature Dish', 'description' => 'Our chef\'s special creation', 'price' => '$24.00' ],
            [ 'name' => 'Classic Favorite', 'description' => 'A timeless customer favorite', 'price' => '$18.00' ],
            [ 'name' => 'Seasonal Special', 'description' => 'Fresh seasonal ingredients', 'price' => '$22.00' ],
        ];

        $content = $this->build_menu_content( $params, $menu_items );

        return $this->create_page( 'Menu', 'menu', [], array_merge( $params, [ 'raw_content' => $content ] ) );
    }

    /**
     * Build restaurant menu content
     */
    private function build_menu_content( $params, $items ) {
        $headline = $params['page_content']['headline'] ?? 'Our Menu';

        $content = '<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)">
<!-- wp:heading {"textAlign":"center","level":1} -->
<h1 class="wp-block-heading has-text-align-center">' . esc_html( $headline ) . '</h1>
<!-- /wp:heading -->

<!-- wp:spacer {"height":"40px"} -->
<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->';

        foreach ( $items as $item ) {
            $content .= '
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}},"border":{"bottom":{"color":"var:preset|color|secondary","width":"1px"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group" style="border-bottom-color:var(--wp--preset--color--secondary);border-bottom-width:1px;padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)">
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group">
<!-- wp:heading {"level":3,"fontSize":"medium"} -->
<h3 class="wp-block-heading has-medium-font-size">' . esc_html( $item['name'] ) . '</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"secondary"} -->
<p class="has-secondary-color has-text-color">' . esc_html( $item['description'] ) . '</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->

<!-- wp:paragraph {"style":{"typography":{"fontWeight":"600"}},"fontSize":"medium"} -->
<p class="has-medium-font-size" style="font-weight:600">' . esc_html( $item['price'] ) . '</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->';
        }

        $content .= '
</div>
<!-- /wp:group -->';

        return $content;
    }

    /**
     * Delete all generated pages
     */
    public function delete_generated_pages() {
        $args = [
            'post_type'      => 'page',
            'posts_per_page' => -1,
            'meta_key'       => '_presspilot_generated',
            'meta_value'     => true,
            'fields'         => 'ids',
        ];

        $pages = get_posts( $args );

        foreach ( $pages as $page_id ) {
            wp_delete_post( $page_id, true );
        }

        return count( $pages );
    }
}
