<?php
/**
 * MooZoo Pizza – core theme functions
 * Generated by PressPilot Theme Generator V1.1
 */

if ( ! function_exists( 'presspilot_moozoo_pizza_setup' ) ) :
	function presspilot_moozoo_pizza_setup() {
		add_theme_support( 'wp-block-styles' );
		add_theme_support( 'editor-styles' );
		add_theme_support( 'block-templates' );
		add_theme_support( 'responsive-embeds' );
		add_theme_support( 'title-tag' );
		add_theme_support( 'menus' );
		add_theme_support( 'post-thumbnails' );
		add_theme_support( 'automatic-feed-links' );
	}
endif;
add_action( 'after_setup_theme', 'presspilot_moozoo_pizza_setup' );

/**
 * Pattern category.
 */
function presspilot_moozoo_pizza_register_pattern_category() {
	register_block_pattern_category(
		'presspilot-moozoo-pizza',
		array(
			'label' => __( 'PressPilot / MooZoo Pizza', 'presspilot-moozoo-pizza' ),
		)
	);
}
add_action( 'init', 'presspilot_moozoo_pizza_register_pattern_category' );

/**
 * Register DB Prefix Endpoint.
 */
function presspilot_moozoo_pizza_register_db_prefix_endpoint() {
    register_rest_route( 'presspilot/v1', '/db-prefix', array(
        'methods'  => 'GET',
        'callback' => function() {
            global $wpdb;
            return array( 'table_prefix' => $wpdb->prefix );
        },
        'permission_callback' => '__return_true',
    ) );
}
add_action( 'rest_api_init', 'presspilot_moozoo_pizza_register_db_prefix_endpoint' );

/**
 * V1.1 Activation Logic
 * - Destructive Mode
 * - Content Generation
 * - Navigation Creation
 */
add_action( 'after_switch_theme', 'presspilot_moozoo_pizza_activate' );

function presspilot_moozoo_pizza_activate() {
    // Injected Config
    $destructive_mode = true;
    $site_title = 'MooZoo Pizza & Design';

    // 1. Destructive mode: trash existing pages and wp_navigation posts.
    if ( $destructive_mode ) {
        $existing_pages = get_posts( array(
            'post_type'      => 'page',
            'posts_per_page' => -1,
            'post_status'    => 'any',
        ) );

        foreach ( $existing_pages as $page ) {
            wp_trash_post( $page->ID );
        }

        $existing_navs = get_posts( array(
            'post_type'      => 'wp_navigation',
            'posts_per_page' => -1,
            'post_status'    => 'any',
        ) );

        foreach ( $existing_navs as $nav ) {
            wp_trash_post( $nav->ID );
        }
    }

    // 2. Create pages from config.
    $pages_to_create = array(
        'home' => array( 'title' => 'Home', 'content' => 'Welcome to MooZoo Pizza.' ),
        'about' => array( 'title' => 'About', 'content' => 'Our story.' ),
        'contact' => array( 'title' => 'Contact', 'content' => 'Get in touch.' ),
        'menu' => array( 'title' => 'Menu', 'content' => 'Our delicious pizzas.' ),
        'services' => array( 'title' => 'Services', 'content' => 'Catering and more.' ),
    );

    $created_page_ids = array();

    foreach ( $pages_to_create as $slug => $data ) {
        // Check if page exists (if not destructive) to avoid duplicates
        $existing = get_page_by_path( $slug );
        if ( $existing ) {
            $created_page_ids[ $slug ] = $existing->ID;
            continue;
        }

        $page_id = wp_insert_post( array(
            'post_type'    => 'page',
            'post_title'   => $data['title'],
            'post_name'    => $slug,
            'post_content' => $data['content'],
            'post_status'  => 'publish',
        ) );

        if ( ! is_wp_error( $page_id ) ) {
            $created_page_ids[ $slug ] = $page_id;
        }
    }

    // 3. Set front page to "home" if it exists.
    if ( isset( $created_page_ids['home'] ) ) {
        update_option( 'show_on_front', 'page' );
        update_option( 'page_on_front', $created_page_ids['home'] );
    }

    // 4. ALWAYS: create a wp_navigation entity for the new pages.
    if ( ! empty( $created_page_ids ) ) {
        $nav_content = '<!-- wp:navigation -->';

        foreach ( $created_page_ids as $slug => $id ) {
            $nav_content .= sprintf(
                '<!-- wp:navigation-link {"label":"%s","type":"page","id":%d} /-->',
                esc_html( get_the_title( $id ) ),
                $id
            );
        }

        $nav_content .= '<!-- /wp:navigation -->';

        wp_insert_post( array(
            'post_type'    => 'wp_navigation',
            'post_title'   => 'Main Navigation (AI)',
            'post_status'  => 'publish',
            'post_content' => $nav_content,
        ) );
    }

    // 5. Set Site Title
    update_option( 'blogname', $site_title );
}
