<?php
/**
 * Title: Universal Heavy Landing
 * Slug: presspilot/universal-heavy
 * Description: A heavy content landing page compatible with any FSE chassis.
 * Categories: featured
 * Keywords: landing, home, heavy, content
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"5rem","bottom":"5rem"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:5rem;padding-bottom:5rem">
    <!-- wp:heading {"textAlign":"center","level":1,"fontSize":"x-large"} -->
    <h1 class="wp-block-heading has-text-align-center has-x-large-font-size">Launch Your Vision</h1>
    <!-- /wp:heading -->

    <!-- wp:paragraph {"align":"center","fontSize":"large"} -->
    <p class="has-text-align-center has-large-font-size">A scalable, modern foundation generated by PressPilot.</p>
    <!-- /wp:paragraph -->

    <!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
    <div class="wp-block-buttons">
        <!-- wp:button -->
        <div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Get Started</a></div>
        <!-- /wp:button -->
        <!-- wp:button {"className":"is-style-outline"} -->
        <div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button">Learn More</a>
        </div>
        <!-- /wp:button -->
    </div>
    <!-- /wp:buttons -->
</div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"4rem","bottom":"4rem"},"margin":{"top":"0","bottom":"0"}},"color":{"background":"var:preset|color|tertiary"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-tertiary-background-color has-background"
    style="margin-top:0;margin-bottom:0;padding-top:4rem;padding-bottom:4rem">
    <!-- wp:columns {"align":"wide"} -->
    <div class="wp-block-columns alignwide">
        <!-- wp:column -->
        <div class="wp-block-column">
            <!-- wp:heading {"level":3} -->
            <h3 class="wp-block-heading">Speed</h3>
            <!-- /wp:heading -->
            <!-- wp:paragraph -->
            <p>Optimized for performance with zero bloat. Runs on native blocks.</p>
            <!-- /wp:paragraph -->
        </div>
        <!-- /wp:column -->

        <!-- wp:column -->
        <div class="wp-block-column">
            <!-- wp:heading {"level":3} -->
            <h3 class="wp-block-heading">Scale</h3>
            <!-- /wp:heading -->
            <!-- wp:paragraph -->
            <p>Built to grow with your business. Modular architecture.</p>
            <!-- /wp:paragraph -->
        </div>
        <!-- /wp:column -->

        <!-- wp:column -->
        <div class="wp-block-column">
            <!-- wp:heading {"level":3} -->
            <h3 class="wp-block-heading">Security</h3>
            <!-- /wp:heading -->
            <!-- wp:paragraph -->
            <p>Secure by default. No plugin dependencies or vulnerabilities.</p>
            <!-- /wp:paragraph -->
        </div>
        <!-- /wp:column -->
    </div>
    <!-- /wp:columns -->
</div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"4rem","bottom":"4rem"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:4rem;padding-bottom:4rem">
    <!-- wp:quote {"textAlign":"center","style":{"typography":{"fontSize":"large"}}} -->
    <blockquote class="wp-block-quote has-text-align-center" style="font-size:large">
        <p>"This platform completely transformed our workflow. The generated themes are clean, fast, and remarkably easy
            to customize."</p>
        <cite>Happy Customer</cite>
    </blockquote>
    <!-- /wp:quote -->
</div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"color":{"background":"var:preset|color|primary","text":"var:preset|color|base"},"spacing":{"padding":{"top":"5rem","bottom":"5rem"},"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-base-color has-primary-background-color has-text-color has-background"
    style="margin-top:0;margin-bottom:0;padding-top:5rem;padding-bottom:5rem">
    <!-- wp:heading {"textAlign":"center"} -->
    <h2 class="wp-block-heading has-text-align-center">Ready to Deploy?</h2>
    <!-- /wp:heading -->
    <!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
    <div class="wp-block-buttons">
        <!-- wp:button {"className":"is-style-outline","style":{"color":{"text":"var:preset|color|base"},"border":{"color":"var:preset|color|base"}}} -->
        <div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button"
                style="color:var(--wp--preset--color--base);border-color:var(--wp--preset--color--base)">Start Now</a>
        </div>
        <!-- /wp:button -->
    </div>
    <!-- /wp:buttons -->
</div>
<!-- /wp:group -->