<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;
use RuntimeException;
use ZipArchive;

class ThemeAssembler
{
    /**
     * The active proven-core slug. Defaults to 'ollie'.
     * Determines which core's theme.json is loaded and which base files are copied.
     */
    private string $coreSlug = 'ollie';

    /**
     * Set the target proven-core for theme assembly.
     * Must be called before assemble() when using a non-Ollie core.
     */
    public function setCore(string $coreSlug): self
    {
        $this->coreSlug = $coreSlug;
        Log::info('ThemeAssembler: Core set', ['core' => $coreSlug]);

        return $this;
    }

    /**
     * @param  array<string, mixed>  $project
     * @param  array<string, string>  $tokens  All tokens (text + image)
     * @param  array<string, string>  $pageHtml  Injected HTML keyed by page type (home, about, services, contact)
     * @return array{themeDir: string, zipPath: string}
     */
    public function assemble(array $project, array $tokens, array $pageHtml): array
    {
        $slug = $this->resolveSlug($project);
        $themeDir = sys_get_temp_dir()."/pp-themes/{$slug}";

        $this->resetDirectory($themeDir);
        $this->copyBaseFiles($themeDir);
        $this->saveLogoAsset($themeDir, $project);
        $this->writeFunctionsPhp($themeDir, $project);
        $this->writeStyleSheet($themeDir, $project);
        $this->writeThemeJson($themeDir, $project);
        $this->writeTemplates($themeDir, $pageHtml, $project);
        $this->writeParts($themeDir, $project, $tokens);

        $zipPath = $this->zipTheme($themeDir, $slug);

        return [
            'themeDir' => $themeDir,
            'zipPath' => $zipPath,
        ];
    }

    private function resolveSlug(array $project): string
    {
        $slug = $project['slug'] ?? $project['name'] ?? 'presspilot-theme';
        $slug = strtolower(trim((string) $slug));
        $slug = preg_replace('/[^a-z0-9\-]+/', '-', $slug) ?? 'presspilot-theme';

        return trim($slug, '-');
    }

    private function resetDirectory(string $themeDir): void
    {
        if (is_dir($themeDir)) {
            $this->deleteDirectory($themeDir);
        }

        if (! mkdir($themeDir, 0755, true) && ! is_dir($themeDir)) {
            throw new RuntimeException("Unable to create theme directory at {$themeDir}");
        }
    }

    public function deleteDirectory(string $directory): void
    {
        $items = array_diff(scandir($directory) ?: [], ['.', '..']);

        foreach ($items as $item) {
            $path = $directory.DIRECTORY_SEPARATOR.$item;

            if (is_dir($path)) {
                $this->deleteDirectory($path);
            } else {
                unlink($path);
            }
        }

        rmdir($directory);
    }

    private function copyBaseFiles(string $themeDir): void
    {
        $baseDir = base_path('../proven-cores/' . $this->coreSlug);
        $baseFiles = ['index.php'];

        foreach ($baseFiles as $file) {
            $source = $baseDir.DIRECTORY_SEPARATOR.$file;
            $destination = $themeDir.DIRECTORY_SEPARATOR.$file;

            if (! file_exists($source)) {
                throw new RuntimeException("Base file missing: {$source}");
            }

            copy($source, $destination);
        }
    }

    /**
     * Generate functions.php with programmatic content setup.
     *
     * Uses an `init` hook with a one-time execution guard to create pages,
     * set blogname/tagline, create nav menu, and configure the front page.
     * This works in ALL WordPress environments including Playground,
     * unlike starter-content which only works through the Customizer.
     *
     * @param  string  $themeDir
     * @param  array<string, mixed>  $project
     */
    private function writeFunctionsPhp(string $themeDir, array $project): void
    {
        $businessName = addslashes((string) ($project['name'] ?? 'PressPilot'));
        $tagline = addslashes((string) ($project['tagline'] ?? ''));
        $vertical = $project['vertical'] ?? null;

        // Build pages config array
        $pagesConfig = [
            ['title' => 'Home', 'template' => 'front-page'],
            ['title' => 'About', 'template' => 'page-about'],
            ['title' => 'Services', 'template' => 'page-services'],
            ['title' => 'Contact', 'template' => 'page-contact'],
        ];

        if ($vertical === 'restaurant') {
            $pagesConfig[] = ['title' => 'Menu', 'template' => 'page-menu'];
        }

        // Generate PHP array literal for pages
        $pagesPhpArray = "[\n";
        foreach ($pagesConfig as $page) {
            $pagesPhpArray .= "            ['title' => '{$page['title']}', 'template' => '{$page['template']}'],\n";
        }
        $pagesPhpArray .= "        ]";

        $functionsContent = <<<PHP
<?php
/**
 * {$businessName} Theme - Functions
 * Generated by PressPilot
 */

// Programmatic content setup — runs once on theme activation
// Works in all WordPress environments including Playground
add_action('init', function() {
    // One-time guard: only run once per theme activation
    if (get_option('_presspilot_content_loaded')) {
        return;
    }

    // Set site title and tagline
    update_option('blogname', '{$businessName}');
    update_option('blogdescription', '{$tagline}');

    // Remove ALL existing default content (pages + posts)
    // Covers every WordPress environment (standard "Hello world!",
    // Playground "Hello from WordPress Playground!", "Sample Page", etc.)
    \$defaultContent = get_posts([
        'post_type'   => ['post', 'page'],
        'numberposts' => -1,
        'post_status' => 'any',
    ]);
    foreach (\$defaultContent as \$item) {
        wp_delete_post(\$item->ID, true);
    }

    // Define pages to create
    \$pages = {$pagesPhpArray};

    \$createdPages = [];
    \$order = 0;

    foreach (\$pages as \$pageConfig) {
        // Check if page already exists
        \$existing = get_page_by_title(\$pageConfig['title'], OBJECT, 'page');
        if (\$existing) {
            \$createdPages[\$pageConfig['title']] = \$existing->ID;
            // Ensure template and menu order are set
            update_post_meta(\$existing->ID, '_wp_page_template', \$pageConfig['template']);
            wp_update_post(['ID' => \$existing->ID, 'menu_order' => \$order]);
            \$order++;
            continue;
        }

        \$pageId = wp_insert_post([
            'post_title'   => \$pageConfig['title'],
            'post_status'  => 'publish',
            'post_type'    => 'page',
            'page_template' => \$pageConfig['template'],
            'menu_order'   => \$order,
        ]);
        \$order++;

        if (\$pageId && !is_wp_error(\$pageId)) {
            update_post_meta(\$pageId, '_wp_page_template', \$pageConfig['template']);
            \$createdPages[\$pageConfig['title']] = \$pageId;
        }
    }

    // Set Home page as static front page
    if (isset(\$createdPages['Home'])) {
        update_option('show_on_front', 'page');
        update_option('page_on_front', \$createdPages['Home']);
    }

    // Create navigation menu
    \$menuName = 'Primary';
    \$menuExists = wp_get_nav_menu_object(\$menuName);
    if (!\$menuExists) {
        \$menuId = wp_create_nav_menu(\$menuName);
        if (\$menuId && !is_wp_error(\$menuId)) {
            \$order = 0;
            foreach (\$createdPages as \$title => \$pageId) {
                \$order += 10;
                wp_update_nav_menu_item(\$menuId, 0, [
                    'menu-item-title'     => \$title,
                    'menu-item-object'    => 'page',
                    'menu-item-object-id' => \$pageId,
                    'menu-item-type'      => 'post_type',
                    'menu-item-status'    => 'publish',
                    'menu-item-position'  => \$order,
                ]);
            }

            // Assign menu to primary location
            \$locations = get_theme_mod('nav_menu_locations', []);
            \$locations['primary'] = \$menuId;
            set_theme_mod('nav_menu_locations', \$locations);
        }
    }

    // Set up site logo from theme assets
    \$logoFile = get_template_directory() . '/assets/{$this->getLogoFilename($project)}';
    if (file_exists(\$logoFile) && !get_theme_mod('custom_logo')) {
        require_once(ABSPATH . 'wp-admin/includes/image.php');
        require_once(ABSPATH . 'wp-admin/includes/file.php');
        require_once(ABSPATH . 'wp-admin/includes/media.php');

        // Copy to temp location since media_handle_sideload moves the file
        \$tmp = wp_tempnam(\$logoFile);
        copy(\$logoFile, \$tmp);
        \$fileArray = [
            'name'     => basename(\$logoFile),
            'tmp_name' => \$tmp,
        ];
        \$attachmentId = media_handle_sideload(\$fileArray, 0);
        if (!\is_wp_error(\$attachmentId)) {
            set_theme_mod('custom_logo', \$attachmentId);
        }
    }

    // Mark as done so this only runs once
    update_option('_presspilot_content_loaded', true);
}, 1);
PHP;

        file_put_contents($themeDir.'/functions.php', $functionsContent);
    }

    private function writeStyleSheet(string $themeDir, array $project): void
    {
        $name = (string) ($project['name'] ?? 'PressPilot Theme');
        $slug = $this->resolveSlug($project);

        $header = "/*\n".
            "Theme Name: {$name} Theme\n".
            "Theme URI: https://presspilotapp.com\n".
            "Author: PressPilot\n".
            "Author URI: https://presspilotapp.com\n".
            "Description: Custom FSE theme for {$name}\n".
            "Version: 1.0.0\n".
            "Requires at least: 6.0\n".
            "Tested up to: 6.4\n".
            "Requires PHP: 7.4\n".
            "License: GNU General Public License v2 or later\n".
            "License URI: http://www.gnu.org/licenses/gpl-2.0.html\n".
            "Text Domain: {$slug}\n".
            "*/\n";

        file_put_contents($themeDir.'/style.css', $header);
    }

    private function writeThemeJson(string $themeDir, array $project): void
    {
        $basePath = base_path('../proven-cores/' . $this->coreSlug . '/theme.json');

        // Fall back to Ollie if the target core has no theme.json (e.g., blockbase)
        if (! file_exists($basePath)) {
            Log::info('ThemeAssembler: No theme.json for core, falling back to Ollie', ['core' => $this->coreSlug]);
            $basePath = base_path('../proven-cores/ollie/theme.json');
        }

        if (! file_exists($basePath)) {
            throw new RuntimeException('Base theme.json not found.');
        }

        $themeJson = json_decode(file_get_contents($basePath), true, 512, JSON_THROW_ON_ERROR);

        // Override colors from project.
        // CRITICAL: Preserve ALL existing palette entries from proven-core theme.json
        // and only override the brand color values. Ollie patterns reference 24+ color slugs.
        $colors = $project['colors'] ?? [];
        $resolver = app(CorePaletteResolver::class);

        // User brand colors (use provided values or defaults)
        $brandPrimary   = $colors['primary'] ?? '#1e3a5f';
        $brandSecondary = $colors['secondary'] ?? '#4a90d9';
        $brandAccent    = $colors['accent'] ?? '#2ecc71';
        $brandBackground = $colors['background'] ?? '#ffffff';
        $brandForeground = $colors['foreground'] ?? '#333333';

        // Generate derived colors
        $tertiary = $this->lightenColor($brandPrimary, 0.85);  // Light tint of primary
        $borderLight = $this->lightenColor($brandPrimary, 0.90); // Very light tint
        $borderDark = $this->lightenColor($brandPrimary, 0.70);  // Medium tint
        $primaryAccent = $this->lightenColor($brandPrimary, 0.80); // Light accent
        $mainAccent = $this->lightenColor($brandForeground, 0.40); // Lighter text

        // Build COMPLETE Ollie-compatible palette with all slugs that patterns reference
        // This ensures no "Attempt Recovery" errors from missing color variables
        $fullPalette = [
            // Core brand colors (user-provided)
            'primary'               => $brandPrimary,
            'secondary'             => $brandSecondary,
            'primary-alt'           => $brandAccent,
            'accent'                => $brandAccent,
            'base'                  => $brandBackground,
            'main'                  => $brandForeground,

            // Additional brand variants (auto-generated)
            'tertiary'              => $tertiary,
            'foreground'            => $brandForeground,
            'background'            => $brandBackground,
            'contrast'              => '#1a1a1a',

            // Border colors (derived from primary)
            'border'                => $borderLight,
            'border-light'          => $borderLight,
            'border-dark'           => $borderDark,

            // Accent variants (derived)
            'primary-accent'        => $primaryAccent,
            'main-accent'           => $mainAccent,

            // Background variants (for has-*-background-color classes)
            'primary-background'    => $this->lightenColor($brandPrimary, 0.95),
            'secondary-background'  => $this->lightenColor($brandSecondary, 0.95),
            'tertiary-background'   => $this->lightenColor($tertiary, 0.50),
            'base-background'       => $brandBackground,
            'main-background'       => $this->lightenColor($brandForeground, 0.95),
            'border-light-background' => $this->lightenColor($borderLight, 0.50),
            'border-dark-background'  => $this->lightenColor($borderDark, 0.50),

            // Border variants for has-*-border-color classes
            'tertiary-border'       => $tertiary,
            'border-light-border'   => $borderLight,
            'primary-border'        => $brandPrimary,
            'base-border'           => $this->lightenColor($brandBackground, 0.90),

            // Icon and utility colors
            'icon'                  => $brandPrimary,
            'icon-background'       => $this->lightenColor($brandPrimary, 0.95),
            'link'                  => $brandPrimary,
            'text'                  => $brandForeground,
            'inline'                => $brandForeground,
        ];

        // Resolve canonical slugs to target core slugs
        $paletteOverrides = [];
        foreach ($fullPalette as $canonicalSlug => $colorValue) {
            $targetSlug = $resolver->resolve($canonicalSlug, $this->coreSlug);
            $paletteOverrides[$targetSlug] = $colorValue;
        }

        // Step 1: Update existing palette entries from base theme.json with brand colors
        if (isset($themeJson['settings']['color']['palette'])) {
            foreach ($themeJson['settings']['color']['palette'] as $index => $entry) {
                $slug = $entry['slug'] ?? null;
                if ($slug && array_key_exists($slug, $paletteOverrides)) {
                    // Override this color with user brand value
                    $themeJson['settings']['color']['palette'][$index]['color'] = $paletteOverrides[$slug];
                    unset($paletteOverrides[$slug]); // Mark as processed
                }
            }
        } else {
            $themeJson['settings']['color']['palette'] = [];
        }

        // Step 2: Add any missing slugs that patterns reference but aren't in base theme.json
        foreach ($paletteOverrides as $slug => $color) {
            $themeJson['settings']['color']['palette'][] = [
                'slug'  => $slug,
                'color' => $color,
                'name'  => ucfirst(str_replace('-', ' ', $slug)),
            ];
            Log::info("ThemeAssembler: Added missing palette slug '{$slug}' = {$color}");
        }

        // Override font families (heading + body pairing if available, else single font)
        $fontPairing = $project['fontPairing'] ?? null;
        $fontFamily = $project['fontFamily'] ?? ($project['fonts']['primary'] ?? null);

        if ($fontPairing && isset($themeJson['settings']['typography']['fontFamilies'])) {
            // Replace first font family with heading font
            $themeJson['settings']['typography']['fontFamilies'][0] = [
                'fontFamily' => $fontPairing['heading'] . ', system-ui, sans-serif',
                'name' => $fontPairing['heading'],
                'slug' => 'heading',
            ];

            // Add body font as second family (or update existing)
            $bodyEntry = [
                'fontFamily' => $fontPairing['body'] . ', system-ui, sans-serif',
                'name' => $fontPairing['body'],
                'slug' => 'body',
            ];

            // If heading and body are same font, just use one entry with slug "primary"
            if ($fontPairing['heading'] === $fontPairing['body']) {
                $themeJson['settings']['typography']['fontFamilies'][0]['slug'] = 'primary';
            } else {
                // Ensure body font is second entry, replacing or adding
                if (isset($themeJson['settings']['typography']['fontFamilies'][1])) {
                    $themeJson['settings']['typography']['fontFamilies'][1] = $bodyEntry;
                } else {
                    $themeJson['settings']['typography']['fontFamilies'][] = $bodyEntry;
                }
            }

            Log::info('ThemeAssembler: Applied font pairing', [
                'heading' => $fontPairing['heading'],
                'body' => $fontPairing['body'],
            ]);
        } elseif ($fontFamily && isset($themeJson['settings']['typography']['fontFamilies'][0])) {
            // Legacy: single font override (backward compatible)
            $themeJson['settings']['typography']['fontFamilies'][0]['fontFamily'] = $fontFamily . ', system-ui, sans-serif';
            $themeJson['settings']['typography']['fontFamilies'][0]['name'] = $fontFamily;
        }

        // Add custom templates registration
        $customTemplates = [
            ['name' => 'page-about', 'title' => 'About', 'postTypes' => ['page']],
            ['name' => 'page-services', 'title' => 'Services', 'postTypes' => ['page']],
            ['name' => 'page-contact', 'title' => 'Contact', 'postTypes' => ['page']],
        ];

        // Add menu template if this is a restaurant vertical
        $vertical = $project['vertical'] ?? null;
        if ($vertical === 'restaurant') {
            $customTemplates[] = ['name' => 'page-menu', 'title' => 'Menu', 'postTypes' => ['page']];
        }

        $themeJson['customTemplates'] = $customTemplates;

        // Ensure templateParts are registered
        $themeJson['templateParts'] = [
            ['name' => 'header', 'area' => 'header', 'title' => 'Header'],
            ['name' => 'header-transparent', 'area' => 'header', 'title' => 'Header Transparent'],
            ['name' => 'footer', 'area' => 'footer', 'title' => 'Footer'],
        ];

        // Add layout settings (contentSize and wideSize)
        if (!isset($themeJson['settings']['layout'])) {
            $themeJson['settings']['layout'] = [];
        }
        $themeJson['settings']['layout']['contentSize'] = '1200px';
        $themeJson['settings']['layout']['wideSize'] = '1400px';

        file_put_contents($themeDir.'/theme.json', json_encode($themeJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    /**
     * Write all template files from injected page HTML.
     *
     * @param  array<string, string>  $pageHtml  Keyed by page type
     * @param  array<string, mixed>  $project  Project data including heroLayout
     */
    private function writeTemplates(string $themeDir, array $pageHtml, ?array $project = null): void
    {
        $templatesDir = $themeDir.'/templates';
        if (! is_dir($templatesDir)) {
            mkdir($templatesDir, 0755, true);
        }

        // front-page.html — uses home page sections
        // For fullBleed hero layout, the hero skeleton already contains its own
        // header (site-title + navigation) inside the wp:cover block, so we must
        // skip the external header-transparent template part to avoid TWO headers.
        $homeContent = $pageHtml['home'] ?? '';
        $heroLayout  = $project['heroLayout'] ?? $project['hero_layout'] ?? null;
        $skipHeader  = ($heroLayout === 'fullBleed');

        Log::info('ThemeAssembler::writeTemplates heroLayout decision', [
            'heroLayout' => $heroLayout,
            'skipHeader' => $skipHeader,
        ]);

        file_put_contents($templatesDir.'/front-page.html', $this->wrapTemplate($homeContent, $skipHeader));

        // Inner pages use the standard (opaque) header since page-banner provides
        // the visual impact. This gives a clean white header → colored banner flow.
        $aboutContent = $pageHtml['about'] ?? '';
        file_put_contents($templatesDir.'/page-about.html', $this->wrapTemplate($aboutContent, false, 'header'));

        if (isset($pageHtml['menu'])) {
            $menuContent = $pageHtml['menu'];
            file_put_contents($templatesDir.'/page-menu.html', $this->wrapTemplate($menuContent, false, 'header'));
        }

        $servicesContent = $pageHtml['services'] ?? '';
        file_put_contents($templatesDir.'/page-services.html', $this->wrapTemplate($servicesContent, false, 'header'));

        $contactContent = $pageHtml['contact'] ?? '';
        file_put_contents($templatesDir.'/page-contact.html', $this->wrapTemplate($contactContent, false, 'header'));

        // Generic fallback templates
        file_put_contents($templatesDir.'/page.html', $this->defaultPageTemplate());
        file_put_contents($templatesDir.'/single.html', $this->defaultSingleTemplate());
        file_put_contents($templatesDir.'/404.html', $this->default404Template());
        file_put_contents($templatesDir.'/index.html', $this->defaultIndexTemplate());
    }

    /**
     * Write header and footer parts.
     */
    private function writeParts(string $themeDir, array $project, array $tokens): void
    {
        $partsDir = $themeDir.'/parts';
        if (! is_dir($partsDir)) {
            mkdir($partsDir, 0755, true);
        }

        file_put_contents($partsDir.'/header.html', $this->buildHeader($project));
        file_put_contents($partsDir.'/header-transparent.html', $this->buildHeaderTransparent($project));
        file_put_contents($partsDir.'/footer.html', $this->buildPressPilotFooter($project, $tokens));
    }

    /**
     * Build the PressPilot branded 3-column footer.
     * Uses CorePaletteResolver to emit correct color slugs for the active core.
     */
    private function buildPressPilotFooter(array $project, array $tokens): string
    {
        $businessName = htmlspecialchars((string) ($project['name'] ?? 'Business'), ENT_QUOTES, 'UTF-8');
        $footerTagline = htmlspecialchars((string) ($tokens['FOOTER_TAGLINE'] ?? "Welcome to {$businessName}"), ENT_QUOTES, 'UTF-8');
        $contactText = htmlspecialchars((string) ($tokens['CONTACT_TEXT'] ?? "Get in touch with us today."), ENT_QUOTES, 'UTF-8');
        $year = date('Y');
        $logoSaved = $project['_logo_saved'] ?? false;

        // Use wp:site-logo block for footer too — matches header, no block validation issues
        $logoBlock = '';
        if ($logoSaved) {
            $logoBlock = '<!-- wp:site-logo {"width":60,"shouldSyncIcon":true} /-->';
        }

        // Resolve color slugs for the active core
        $resolver = app(CorePaletteResolver::class);
        $bgColor     = $resolver->resolve('tertiary', $this->coreSlug);
        $darkText    = $resolver->resolve('main', $this->coreSlug);
        $mutedText   = 'foreground';

        $footer = <<<FOOTER
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|50"}}},"backgroundColor":"{$bgColor}","textColor":"{$darkText}","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-{$darkText}-color has-{$bgColor}-background-color has-text-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--50)">

    <!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} -->
    <div class="wp-block-columns alignwide">
        <!-- wp:column {"width":"33%"} -->
        <div class="wp-block-column" style="flex-basis:33%">
            <!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"center"}} -->
            <div class="wp-block-group">
                {$logoBlock}
                <!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem"}},"layout":{"type":"flex","orientation":"vertical"}} -->
                <div class="wp-block-group">
                    <!-- wp:site-title {"style":{"typography":{"fontStyle":"normal","fontWeight":"700","fontSize":"1.25rem"}}} /-->
                    <!-- wp:paragraph {"fontSize":"small","textColor":"{$mutedText}"} -->
                    <p class="has-small-font-size has-{$mutedText}-color has-text-color">{$footerTagline}</p>
                    <!-- /wp:paragraph -->
                </div>
                <!-- /wp:group -->
            </div>
            <!-- /wp:group -->
        </div>
        <!-- /wp:column -->
        <!-- wp:column {"width":"33%"} -->
        <div class="wp-block-column" style="flex-basis:33%">
            <!-- wp:heading {"level":4,"textColor":"{$darkText}","style":{"typography":{"fontWeight":"700","textTransform":"uppercase","letterSpacing":"1px"}},"fontSize":"small"} -->
            <h4 class="wp-block-heading has-small-font-size has-{$darkText}-color has-text-color" style="font-weight:700;text-transform:uppercase;letter-spacing:1px">Quick Links</h4>
            <!-- /wp:heading -->
            <!-- wp:navigation {"overlayMenu":"never","layout":{"type":"flex","orientation":"vertical"},"fontSize":"small","style":{"spacing":{"blockGap":"0.75rem"}}} /-->
        </div>
        <!-- /wp:column -->
        <!-- wp:column {"width":"33%"} -->
        <div class="wp-block-column" style="flex-basis:33%">
            <!-- wp:heading {"level":4,"textColor":"{$darkText}","style":{"typography":{"fontWeight":"700","textTransform":"uppercase","letterSpacing":"1px"}},"fontSize":"small"} -->
            <h4 class="wp-block-heading has-small-font-size has-{$darkText}-color has-text-color" style="font-weight:700;text-transform:uppercase;letter-spacing:1px">Get In Touch</h4>
            <!-- /wp:heading -->
            <!-- wp:paragraph {"fontSize":"small","textColor":"{$mutedText}"} -->
            <p class="has-small-font-size has-{$mutedText}-color has-text-color">{$contactText}</p>
            <!-- /wp:paragraph -->
            <!-- wp:social-links {"iconColor":"{$darkText}","iconColorValue":"currentColor","size":"has-normal-icon-size","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}},"className":"is-style-logos-only"} -->
            <ul class="wp-block-social-links has-normal-icon-size has-icon-color is-style-logos-only">
                <!-- wp:social-link {"url":"#","service":"facebook"} /-->
                <!-- wp:social-link {"url":"#","service":"x"} /-->
                <!-- wp:social-link {"url":"#","service":"instagram"} /-->
            </ul>
            <!-- /wp:social-links -->
        </div>
        <!-- /wp:column -->
    </div>
    <!-- /wp:columns -->

    <!-- wp:spacer {"height":"var:preset|spacing|50"} -->
    <div style="height:var(--wp--preset--spacing--50)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->

    <!-- wp:paragraph {"align":"center","fontSize":"small","textColor":"{$mutedText}"} -->
    <p class="has-text-align-center has-small-font-size has-{$mutedText}-color has-text-color">&copy; {$year} {$businessName}. All rights reserved. Powered by <a href="https://www.presspilotapp.com" target="_blank" rel="noopener noreferrer" style="color:inherit">PressPilot</a>.</p>
    <!-- /wp:paragraph -->

</div>
<!-- /wp:group -->
FOOTER;

        // Apply text color enforcement rules
        $tokenInjector = app(TokenInjector::class);
        return $tokenInjector->enforceTextColorRules($footer);
    }

    /**
     * Build header with logo (if available), site title, and navigation block.
     */
    private function buildHeader(array $project): string
    {
        $name = htmlspecialchars((string) ($project['name'] ?? 'PressPilot'), ENT_QUOTES, 'UTF-8');
        $logoSaved = $project['_logo_saved'] ?? false;

        Log::info('ThemeAssembler::buildHeader logo check', [
            'logo_saved' => $logoSaved,
            'logo_filename' => $project['_logo_filename'] ?? null,
        ]);

        // Use wp:site-logo block — self-closing, no inner HTML, no block validation issues.
        // The actual logo image is sideloaded into the media library via functions.php.
        $logoBlock = '';
        if ($logoSaved) {
            $logoBlock = '<!-- wp:site-logo {"width":60,"shouldSyncIcon":true} /-->';
        }

        return <<<HEADER
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50)">
    <!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
    <div class="wp-block-group">
        {$logoBlock}
        <!-- wp:site-title {"level":0,"style":{"typography":{"fontWeight":"700"}}} /-->
    </div>
    <!-- /wp:group -->
    <!-- wp:navigation {"overlayMenu":"never","layout":{"type":"flex","justifyContent":"right"}} /-->
</div>
<!-- /wp:group -->
HEADER;
    }

    /**
     * Build transparent header for fullbleed hero pages with white text.
     */
    private function buildHeaderTransparent(array $project): string
    {
        $name = htmlspecialchars((string) ($project['name'] ?? 'PressPilot'), ENT_QUOTES, 'UTF-8');
        $logoSaved = $project['_logo_saved'] ?? false;

        Log::info('ThemeAssembler::buildHeaderTransparent logo check', [
            'logo_saved' => $logoSaved,
            'logo_filename' => $project['_logo_filename'] ?? null,
        ]);

        // Use wp:site-logo block — self-closing, no inner HTML, no block validation issues.
        // The actual logo image is sideloaded into the media library via functions.php.
        $logoBlock = '';
        if ($logoSaved) {
            $logoBlock = '<!-- wp:site-logo {"width":60,"shouldSyncIcon":true} /-->';
        }

        return <<<HEADER
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50)">
    <!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
    <div class="wp-block-group">
        {$logoBlock}
        <!-- wp:site-title {"level":0,"style":{"typography":{"fontWeight":"700"}},"textColor":"base"} /-->
    </div>
    <!-- /wp:group -->
    <!-- wp:navigation {"overlayMenu":"never","layout":{"type":"flex","justifyContent":"right"},"textColor":"base"} /-->
</div>
<!-- /wp:group -->
HEADER;
    }

    private function wrapTemplate(string $content, bool $skipHeader = false, string $headerSlug = 'header-transparent'): string
    {
        $parts = '';

        if (! $skipHeader) {
            // Add header template part.
            // - 'header-transparent': white text, for pages with dark hero/cover backgrounds
            // - 'header': standard opaque header, for inner pages with page-banner
            // Skipped entirely for fullBleed hero because hero-fullbleed.html
            // already contains its own site-title + navigation inside wp:cover.
            $parts .= "<!-- wp:template-part {\"slug\":\"{$headerSlug}\",\"tagName\":\"header\"} /-->\n\n";
        }

        $parts .= $content."\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";

        return $parts;
    }

    private function defaultPageTemplate(): string
    {
        return "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n".
            "<!-- wp:group {\"tagName\":\"main\"} -->\n".
            "<main class=\"wp-block-group\">\n".
            "<!-- wp:group {\"layout\":{\"type\":\"constrained\"}} -->\n".
            "<div class=\"wp-block-group\">\n".
            "<!-- wp:post-content {\"layout\":{\"type\":\"constrained\"}} /-->\n".
            "</div>\n".
            "<!-- /wp:group -->\n".
            "</main>\n".
            "<!-- /wp:group -->\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function defaultSingleTemplate(): string
    {
        return "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n".
            "<!-- wp:group {\"tagName\":\"main\"} -->\n".
            "<main class=\"wp-block-group\">\n".
            "<!-- wp:group {\"layout\":{\"type\":\"constrained\"}} -->\n".
            "<div class=\"wp-block-group\">\n".
            "<!-- wp:post-title {\"level\":1} /-->\n".
            "<!-- wp:post-content {\"layout\":{\"type\":\"constrained\"}} /-->\n".
            "</div>\n".
            "<!-- /wp:group -->\n".
            "</main>\n".
            "<!-- /wp:group -->\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function default404Template(): string
    {
        return "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n".
            "<!-- wp:group {\"tagName\":\"main\"} -->\n".
            "<main class=\"wp-block-group\">\n".
            "<!-- wp:group {\"layout\":{\"type\":\"constrained\"}} -->\n".
            "<div class=\"wp-block-group\">\n".
            "<!-- wp:heading {\"level\":2} -->\n".
            "<h2 class=\"wp-block-heading\">Page not found</h2>\n".
            "<!-- /wp:heading -->\n".
            "<!-- wp:paragraph -->\n".
            "<p>The page you are looking for could not be found.</p>\n".
            "<!-- /wp:paragraph -->\n".
            "</div>\n".
            "<!-- /wp:group -->\n".
            "</main>\n".
            "<!-- /wp:group -->\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function defaultIndexTemplate(): string
    {
        return "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n".
            "<!-- wp:group {\"tagName\":\"main\"} -->\n".
            "<main class=\"wp-block-group\">\n".
            "<!-- wp:group {\"layout\":{\"type\":\"constrained\"}} -->\n".
            "<div class=\"wp-block-group\">\n".
            "<!-- wp:query {\"queryId\":1,\"query\":{\"perPage\":10,\"pages\":0,\"offset\":0,\"postType\":\"post\",\"order\":\"desc\",\"orderBy\":\"date\",\"author\":\"\",\"search\":\"\",\"exclude\":[],\"sticky\":\"\",\"inherit\":true}} -->\n".
            "<!-- wp:post-template -->\n".
            "<!-- wp:post-title {\"isLink\":true} /-->\n".
            "<!-- wp:post-excerpt /-->\n".
            "<!-- /wp:post-template -->\n".
            "<!-- wp:query-pagination -->\n".
            "<!-- wp:query-pagination-previous /-->\n".
            "<!-- wp:query-pagination-numbers /-->\n".
            "<!-- wp:query-pagination-next /-->\n".
            "<!-- /wp:query-pagination -->\n".
            "<!-- /wp:query -->\n".
            "</div>\n".
            "<!-- /wp:group -->\n".
            "</main>\n".
            "<!-- /wp:group -->\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function zipTheme(string $themeDir, string $slug): string
    {
        $zipPath = sys_get_temp_dir()."/pp-themes/{$slug}.zip";
        $zip = new ZipArchive;

        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new RuntimeException('Unable to create zip archive.');
        }

        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($themeDir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($files as $file) {
            $filePath = $file->getRealPath();
            if (! $filePath) {
                continue;
            }

            $relativePath = substr($filePath, strlen($themeDir) + 1);

            if ($file->isDir()) {
                $zip->addEmptyDir($relativePath);
            } else {
                $zip->addFile($filePath, $relativePath);
            }
        }

        $zip->close();

        return $zipPath;
    }

    /**
     * Save logo from data URI or URL to theme assets directory.
     * Sets $project['_logo_saved'] = true if successfully saved.
     */
    private function saveLogoAsset(string $themeDir, array &$project): void
    {
        $logoUrl = $project['logo'] ?? null;
        if (! $logoUrl || ! is_string($logoUrl)) {
            return;
        }

        $assetsDir = $themeDir.'/assets';
        if (! is_dir($assetsDir)) {
            mkdir($assetsDir, 0755, true);
        }

        // Handle data:image URIs (base64 from Studio upload)
        if (str_starts_with($logoUrl, 'data:image/')) {
            // Extract MIME type and extension
            if (preg_match('/^data:image\/(\w+);base64,(.+)$/s', $logoUrl, $matches)) {
                $ext = $matches[1] === 'jpeg' ? 'jpg' : $matches[1]; // normalize jpeg→jpg
                $decoded = base64_decode($matches[2], true);
                if ($decoded !== false) {
                    $filename = "logo.{$ext}";
                    file_put_contents($assetsDir.'/'.$filename, $decoded);
                    $project['_logo_filename'] = $filename;
                    $project['_logo_saved'] = true;
                    Log::info("ThemeAssembler: Logo saved as assets/{$filename}", [
                        'size' => strlen($decoded),
                    ]);

                    return;
                }
            }
            Log::warning('ThemeAssembler: Failed to decode data URI logo');

            return;
        }

        // Handle http(s) URLs — download the file
        if (filter_var($logoUrl, FILTER_VALIDATE_URL)) {
            try {
                $imageData = @file_get_contents($logoUrl, false, stream_context_create([
                    'http' => ['timeout' => 10],
                ]));
                if ($imageData !== false && strlen($imageData) > 0) {
                    // Detect extension from content type or URL
                    $ext = pathinfo(parse_url($logoUrl, PHP_URL_PATH) ?? '', PATHINFO_EXTENSION) ?: 'png';
                    $ext = strtolower($ext);
                    if (! in_array($ext, ['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'])) {
                        $ext = 'png';
                    }
                    $filename = "logo.{$ext}";
                    file_put_contents($assetsDir.'/'.$filename, $imageData);
                    $project['_logo_filename'] = $filename;
                    $project['_logo_saved'] = true;
                    Log::info("ThemeAssembler: Logo downloaded and saved as assets/{$filename}");

                    return;
                }
            } catch (\Throwable $e) {
                Log::warning('ThemeAssembler: Failed to download logo URL', [
                    'url' => mb_substr($logoUrl, 0, 120),
                    'error' => $e->getMessage(),
                ]);
            }
        }
    }

    /**
     * Get the logo filename from project metadata, with a safe fallback.
     */
    private function getLogoFilename(array $project): string
    {
        return $project['_logo_filename'] ?? 'logo.png';
    }

    /**
     * Check if a logo source is valid for embedding in an <img> src attribute.
     * Accepts both http(s) URLs and data: URIs (base64 logo uploads from Studio).
     */
    private function isValidLogoSource(string $src): bool
    {
        // Accept standard http/https URLs
        if (filter_var($src, FILTER_VALIDATE_URL)) {
            return true;
        }

        // Accept data: URIs (base64-encoded images from Studio upload)
        if (str_starts_with($src, 'data:image/')) {
            return true;
        }

        return false;
    }

    /**
     * Lighten a hex color by blending it with white.
     * Used to generate tertiary color (light tint of primary).
     *
     * @param  string  $hex    Hex color (with or without #)
     * @param  float   $amount Amount to lighten (0.0 = original, 1.0 = white)
     * @return string  Lightened hex color with #
     */
    private function lightenColor(string $hex, float $amount): string
    {
        // Remove # if present
        $hex = ltrim($hex, '#');

        // Convert to RGB
        if (strlen($hex) === 3) {
            $hex = $hex[0].$hex[0].$hex[1].$hex[1].$hex[2].$hex[2];
        }

        $r = hexdec(substr($hex, 0, 2));
        $g = hexdec(substr($hex, 2, 2));
        $b = hexdec(substr($hex, 4, 2));

        // Blend with white (255, 255, 255)
        $r = (int) round($r + ($amount * (255 - $r)));
        $g = (int) round($g + ($amount * (255 - $g)));
        $b = (int) round($b + ($amount * (255 - $b)));

        // Convert back to hex
        return sprintf('#%02x%02x%02x', $r, $g, $b);
    }
}
