<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;
use RuntimeException;
use ZipArchive;

class ThemeAssembler
{
    /**
     * @param  array<string, mixed>  $project
     * @param  array<string, string>  $tokens  All tokens (text + image)
     * @param  array<string, string>  $pageHtml  Injected HTML keyed by page type (home, about, services, contact)
     * @return array{themeDir: string, zipPath: string}
     */
    public function assemble(array $project, array $tokens, array $pageHtml): array
    {
        $slug = $this->resolveSlug($project);
        $themeDir = sys_get_temp_dir()."/pp-themes/{$slug}";

        $this->resetDirectory($themeDir);
        $this->copyBaseFiles($themeDir);
        $this->writeFunctionsPhp($themeDir, $project);
        $this->writeStyleSheet($themeDir, $project);
        $this->writeThemeJson($themeDir, $project);
        $this->writeTemplates($themeDir, $pageHtml, $project);
        $this->writeParts($themeDir, $project, $tokens);

        $zipPath = $this->zipTheme($themeDir, $slug);

        return [
            'themeDir' => $themeDir,
            'zipPath' => $zipPath,
        ];
    }

    private function resolveSlug(array $project): string
    {
        $slug = $project['slug'] ?? $project['name'] ?? 'presspilot-theme';
        $slug = strtolower(trim((string) $slug));
        $slug = preg_replace('/[^a-z0-9\-]+/', '-', $slug) ?? 'presspilot-theme';

        return trim($slug, '-');
    }

    private function resetDirectory(string $themeDir): void
    {
        if (is_dir($themeDir)) {
            $this->deleteDirectory($themeDir);
        }

        if (! mkdir($themeDir, 0755, true) && ! is_dir($themeDir)) {
            throw new RuntimeException("Unable to create theme directory at {$themeDir}");
        }
    }

    public function deleteDirectory(string $directory): void
    {
        $items = array_diff(scandir($directory) ?: [], ['.', '..']);

        foreach ($items as $item) {
            $path = $directory.DIRECTORY_SEPARATOR.$item;

            if (is_dir($path)) {
                $this->deleteDirectory($path);
            } else {
                unlink($path);
            }
        }

        rmdir($directory);
    }

    private function copyBaseFiles(string $themeDir): void
    {
        $baseDir = base_path('../proven-cores/ollie');
        $baseFiles = ['index.php'];

        foreach ($baseFiles as $file) {
            $source = $baseDir.DIRECTORY_SEPARATOR.$file;
            $destination = $themeDir.DIRECTORY_SEPARATOR.$file;

            if (! file_exists($source)) {
                throw new RuntimeException("Base file missing: {$source}");
            }

            copy($source, $destination);
        }
    }

    /**
     * Generate functions.php with programmatic content setup.
     *
     * Uses an `init` hook with a one-time execution guard to create pages,
     * set blogname/tagline, create nav menu, and configure the front page.
     * This works in ALL WordPress environments including Playground,
     * unlike starter-content which only works through the Customizer.
     *
     * @param  string  $themeDir
     * @param  array<string, mixed>  $project
     */
    private function writeFunctionsPhp(string $themeDir, array $project): void
    {
        $businessName = addslashes((string) ($project['name'] ?? 'PressPilot'));
        $tagline = addslashes((string) ($project['tagline'] ?? ''));
        $vertical = $project['vertical'] ?? null;

        // Build pages config array
        $pagesConfig = [
            ['title' => 'Home', 'template' => 'front-page'],
            ['title' => 'About', 'template' => 'page-about'],
            ['title' => 'Services', 'template' => 'page-services'],
            ['title' => 'Contact', 'template' => 'page-contact'],
        ];

        if ($vertical === 'restaurant') {
            $pagesConfig[] = ['title' => 'Menu', 'template' => 'page-menu'];
        }

        // Generate PHP array literal for pages
        $pagesPhpArray = "[\n";
        foreach ($pagesConfig as $page) {
            $pagesPhpArray .= "            ['title' => '{$page['title']}', 'template' => '{$page['template']}'],\n";
        }
        $pagesPhpArray .= "        ]";

        $functionsContent = <<<PHP
<?php
/**
 * {$businessName} Theme - Functions
 * Generated by PressPilot
 */

// Programmatic content setup — runs once on theme activation
// Works in all WordPress environments including Playground
add_action('init', function() {
    // One-time guard: only run once per theme activation
    if (get_option('_presspilot_content_loaded')) {
        return;
    }

    // Set site title and tagline
    update_option('blogname', '{$businessName}');
    update_option('blogdescription', '{$tagline}');

    // Define pages to create
    \$pages = {$pagesPhpArray};

    \$createdPages = [];

    foreach (\$pages as \$pageConfig) {
        // Check if page already exists
        \$existing = get_page_by_title(\$pageConfig['title'], OBJECT, 'page');
        if (\$existing) {
            \$createdPages[\$pageConfig['title']] = \$existing->ID;
            // Ensure template is set
            update_post_meta(\$existing->ID, '_wp_page_template', \$pageConfig['template']);
            continue;
        }

        \$pageId = wp_insert_post([
            'post_title'   => \$pageConfig['title'],
            'post_status'  => 'publish',
            'post_type'    => 'page',
            'page_template' => \$pageConfig['template'],
        ]);

        if (\$pageId && !is_wp_error(\$pageId)) {
            update_post_meta(\$pageId, '_wp_page_template', \$pageConfig['template']);
            \$createdPages[\$pageConfig['title']] = \$pageId;
        }
    }

    // Set Home page as static front page
    if (isset(\$createdPages['Home'])) {
        update_option('show_on_front', 'page');
        update_option('page_on_front', \$createdPages['Home']);
    }

    // Create navigation menu
    \$menuName = 'Primary';
    \$menuExists = wp_get_nav_menu_object(\$menuName);
    if (!\$menuExists) {
        \$menuId = wp_create_nav_menu(\$menuName);
        if (\$menuId && !is_wp_error(\$menuId)) {
            \$order = 0;
            foreach (\$createdPages as \$title => \$pageId) {
                \$order += 10;
                wp_update_nav_menu_item(\$menuId, 0, [
                    'menu-item-title'     => \$title,
                    'menu-item-object'    => 'page',
                    'menu-item-object-id' => \$pageId,
                    'menu-item-type'      => 'post_type',
                    'menu-item-status'    => 'publish',
                    'menu-item-position'  => \$order,
                ]);
            }

            // Assign menu to primary location
            \$locations = get_theme_mod('nav_menu_locations', []);
            \$locations['primary'] = \$menuId;
            set_theme_mod('nav_menu_locations', \$locations);
        }
    }

    // Mark as done so this only runs once
    update_option('_presspilot_content_loaded', true);
}, 1);
PHP;

        file_put_contents($themeDir.'/functions.php', $functionsContent);
    }

    private function writeStyleSheet(string $themeDir, array $project): void
    {
        $name = (string) ($project['name'] ?? 'PressPilot Theme');
        $slug = $this->resolveSlug($project);

        $header = "/*\n".
            "Theme Name: {$name} Theme\n".
            "Theme URI: https://presspilotapp.com\n".
            "Author: PressPilot\n".
            "Author URI: https://presspilotapp.com\n".
            "Description: Custom FSE theme for {$name}\n".
            "Version: 1.0.0\n".
            "Requires at least: 6.0\n".
            "Tested up to: 6.4\n".
            "Requires PHP: 7.4\n".
            "License: GNU General Public License v2 or later\n".
            "License URI: http://www.gnu.org/licenses/gpl-2.0.html\n".
            "Text Domain: {$slug}\n".
            "*/\n";

        file_put_contents($themeDir.'/style.css', $header);
    }

    private function writeThemeJson(string $themeDir, array $project): void
    {
        $basePath = base_path('../proven-cores/ollie/theme.json');
        if (! file_exists($basePath)) {
            throw new RuntimeException('Base theme.json not found.');
        }

        $themeJson = json_decode(file_get_contents($basePath), true, 512, JSON_THROW_ON_ERROR);

        // Override colors from project
        $colors = $project['colors'] ?? [];
        $paletteOverrides = [
            'primary' => $colors['primary'] ?? null,
            'secondary' => $colors['secondary'] ?? null,
            'primary-alt' => $colors['accent'] ?? null,
            'base' => $colors['background'] ?? null,
            'main' => $colors['foreground'] ?? null,
        ];

        if (isset($themeJson['settings']['color']['palette'])) {
            foreach ($themeJson['settings']['color']['palette'] as $index => $entry) {
                $slug = $entry['slug'] ?? null;
                if ($slug && array_key_exists($slug, $paletteOverrides) && $paletteOverrides[$slug]) {
                    $themeJson['settings']['color']['palette'][$index]['color'] = $paletteOverrides[$slug];
                }
            }
        }

        // If NO colors were overridden (all null), apply PressPilot defaults
        $anyColorSet = false;
        foreach ($paletteOverrides as $v) {
            if ($v) {
                $anyColorSet = true;
                break;
            }
        }
        if (! $anyColorSet) {
            Log::info('ThemeAssembler: No brand colors provided, applying PressPilot defaults');
            $defaults = [
                'primary' => '#1e3a5f',
                'secondary' => '#4a90d9',
                'primary-alt' => '#2ecc71',
                'base' => '#ffffff',
                'main' => '#1a1a2e',
            ];
            foreach ($themeJson['settings']['color']['palette'] as $index => $entry) {
                $slug = $entry['slug'] ?? null;
                if ($slug && isset($defaults[$slug])) {
                    $themeJson['settings']['color']['palette'][$index]['color'] = $defaults[$slug];
                }
            }
        }

        // Override font family
        $fontFamily = $project['fontFamily'] ?? ($project['fonts']['primary'] ?? null);
        if ($fontFamily && isset($themeJson['settings']['typography']['fontFamilies'][0])) {
            $themeJson['settings']['typography']['fontFamilies'][0]['fontFamily'] = $fontFamily.', system-ui, sans-serif';
            $themeJson['settings']['typography']['fontFamilies'][0]['name'] = $fontFamily;
        }

        // Add custom templates registration
        $customTemplates = [
            ['name' => 'page-about', 'title' => 'About', 'postTypes' => ['page']],
            ['name' => 'page-services', 'title' => 'Services', 'postTypes' => ['page']],
            ['name' => 'page-contact', 'title' => 'Contact', 'postTypes' => ['page']],
        ];

        // Add menu template if this is a restaurant vertical
        $vertical = $project['vertical'] ?? null;
        if ($vertical === 'restaurant') {
            $customTemplates[] = ['name' => 'page-menu', 'title' => 'Menu', 'postTypes' => ['page']];
        }

        $themeJson['customTemplates'] = $customTemplates;

        // Ensure templateParts are registered
        $themeJson['templateParts'] = [
            ['name' => 'header', 'area' => 'header', 'title' => 'Header'],
            ['name' => 'footer', 'area' => 'footer', 'title' => 'Footer'],
        ];

        file_put_contents($themeDir.'/theme.json', json_encode($themeJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    /**
     * Write all template files from injected page HTML.
     *
     * @param  array<string, string>  $pageHtml  Keyed by page type
     * @param  array<string, mixed>  $project  Project data including heroLayout
     */
    private function writeTemplates(string $themeDir, array $pageHtml, ?array $project = null): void
    {
        $templatesDir = $themeDir.'/templates';
        if (! is_dir($templatesDir)) {
            mkdir($templatesDir, 0755, true);
        }

        // front-page.html — uses home page sections
        $homeContent = $pageHtml['home'] ?? '';
        $isFullBleedHero = $project && ($project['heroLayout'] ?? null) === 'fullBleed';
        file_put_contents($templatesDir.'/front-page.html', $this->wrapTemplate($homeContent, $isFullBleedHero));

        // page-about.html — uses about page sections
        $aboutContent = $pageHtml['about'] ?? '';
        file_put_contents($templatesDir.'/page-about.html', $this->wrapTemplate($aboutContent, false));

        // page-menu.html — uses menu page sections (for restaurant vertical)
        if (isset($pageHtml['menu'])) {
            $menuContent = $pageHtml['menu'];
            file_put_contents($templatesDir.'/page-menu.html', $this->wrapTemplate($menuContent, false));
        }

        // page-services.html — uses services page sections
        $servicesContent = $pageHtml['services'] ?? '';
        file_put_contents($templatesDir.'/page-services.html', $this->wrapTemplate($servicesContent, false));

        // page-contact.html — uses contact page sections
        $contactContent = $pageHtml['contact'] ?? '';
        file_put_contents($templatesDir.'/page-contact.html', $this->wrapTemplate($contactContent, false));

        // Generic fallback templates
        file_put_contents($templatesDir.'/page.html', $this->defaultPageTemplate());
        file_put_contents($templatesDir.'/single.html', $this->defaultSingleTemplate());
        file_put_contents($templatesDir.'/404.html', $this->default404Template());
        file_put_contents($templatesDir.'/index.html', $this->defaultIndexTemplate());
    }

    /**
     * Write header and footer parts.
     */
    private function writeParts(string $themeDir, array $project, array $tokens): void
    {
        $partsDir = $themeDir.'/parts';
        if (! is_dir($partsDir)) {
            mkdir($partsDir, 0755, true);
        }

        file_put_contents($partsDir.'/header.html', $this->buildHeader($project));
        file_put_contents($partsDir.'/footer.html', $this->buildPressPilotFooter($project, $tokens));
    }

    /**
     * Build the PressPilot branded 3-column footer.
     */
    private function buildPressPilotFooter(array $project, array $tokens): string
    {
        $businessName = htmlspecialchars((string) ($project['name'] ?? 'Business'), ENT_QUOTES, 'UTF-8');
        $footerTagline = htmlspecialchars((string) ($tokens['FOOTER_TAGLINE'] ?? "Welcome to {$businessName}"), ENT_QUOTES, 'UTF-8');
        $contactText = htmlspecialchars((string) ($tokens['CONTACT_TEXT'] ?? "Get in touch with us today."), ENT_QUOTES, 'UTF-8');
        $year = date('Y');
        $logoUrl = $project['logo'] ?? null;

        $logoBlock = '';
        if ($logoUrl && filter_var($logoUrl, FILTER_VALIDATE_URL)) {
            $escapedLogo = htmlspecialchars($logoUrl, ENT_QUOTES, 'UTF-8');
            $logoBlock = <<<LOGO
<!-- wp:image {"width":"40px","height":"40px","sizeSlug":"full","style":{"border":{"radius":"4px"}}} -->
<figure class="wp-block-image size-full" style="width:40px;height:40px"><img src="{$escapedLogo}" alt="{$businessName} logo" style="border-radius:4px;width:40px;height:40px;object-fit:contain"/></figure>
<!-- /wp:image -->
LOGO;
        }

        return <<<FOOTER
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|50"}}},"backgroundColor":"base-2","textColor":"contrast","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-contrast-color has-base-2-background-color has-text-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--50)">

    <!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} -->
    <div class="wp-block-columns alignwide">
        <!-- wp:column {"width":"33%"} -->
        <div class="wp-block-column" style="flex-basis:33%">
            <!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","verticalAlignment":"top"}} -->
            <div class="wp-block-group">
                <!-- wp:group {"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
                <div class="wp-block-group">
                    {$logoBlock}
                    <!-- wp:site-title {"style":{"typography":{"fontStyle":"normal","fontWeight":"700","fontSize":"1.5rem"}}} /-->
                    <!-- wp:paragraph {"fontSize":"small","textColor":"contrast-2"} -->
                    <p class="has-small-font-size has-contrast-2-color has-text-color">{$footerTagline}</p>
                    <!-- /wp:paragraph -->
                </div>
                <!-- /wp:group -->
            </div>
            <!-- /wp:group -->
        </div>
        <!-- /wp:column -->
        <!-- wp:column {"width":"33%"} -->
        <div class="wp-block-column" style="flex-basis:33%">
            <!-- wp:heading {"level":4,"textColor":"contrast","style":{"typography":{"fontWeight":"700","textTransform":"uppercase","letterSpacing":"1px"}},"fontSize":"small"} -->
            <h4 class="wp-block-heading has-small-font-size has-contrast-color has-text-color" style="font-weight:700;text-transform:uppercase;letter-spacing:1px">Quick Links</h4>
            <!-- /wp:heading -->
            <!-- wp:navigation {"overlayMenu":"never","layout":{"type":"flex","orientation":"vertical"},"fontSize":"small","style":{"spacing":{"blockGap":"0.75rem"}}} /-->
        </div>
        <!-- /wp:column -->
        <!-- wp:column {"width":"33%"} -->
        <div class="wp-block-column" style="flex-basis:33%">
            <!-- wp:heading {"level":4,"textColor":"contrast","style":{"typography":{"fontWeight":"700","textTransform":"uppercase","letterSpacing":"1px"}},"fontSize":"small"} -->
            <h4 class="wp-block-heading has-small-font-size has-contrast-color has-text-color" style="font-weight:700;text-transform:uppercase;letter-spacing:1px">Get In Touch</h4>
            <!-- /wp:heading -->
            <!-- wp:paragraph {"fontSize":"small","textColor":"contrast-2"} -->
            <p class="has-small-font-size has-contrast-2-color has-text-color">{$contactText}</p>
            <!-- /wp:paragraph -->
            <!-- wp:social-links {"iconColor":"contrast","iconColorValue":"currentColor","size":"has-normal-icon-size","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}},"className":"is-style-logos-only"} -->
            <ul class="wp-block-social-links has-normal-icon-size has-icon-color is-style-logos-only">
                <!-- wp:social-link {"url":"#","service":"facebook"} /-->
                <!-- wp:social-link {"url":"#","service":"x"} /-->
                <!-- wp:social-link {"url":"#","service":"instagram"} /-->
            </ul>
            <!-- /wp:social-links -->
        </div>
        <!-- /wp:column -->
    </div>
    <!-- /wp:columns -->

    <!-- wp:spacer {"height":"var:preset|spacing|50"} -->
    <div style="height:var(--wp--preset--spacing--50)" aria-hidden="true" class="wp-block-spacer"></div>
    <!-- /wp:spacer -->

    <!-- wp:paragraph {"align":"center","fontSize":"small","textColor":"contrast-2"} -->
    <p class="has-text-align-center has-small-font-size has-contrast-2-color has-text-color">&copy; {$year} {$businessName}. All rights reserved. Powered by <a href="https://www.presspilotapp.com" target="_blank" rel="noopener noreferrer" style="color:inherit">PressPilot</a>.</p>
    <!-- /wp:paragraph -->

</div>
<!-- /wp:group -->
FOOTER;
    }

    /**
     * Build header with logo (if available), site title, and navigation block.
     */
    private function buildHeader(array $project): string
    {
        $name = htmlspecialchars((string) ($project['name'] ?? 'PressPilot'), ENT_QUOTES, 'UTF-8');
        $logoUrl = $project['logo'] ?? null;

        $logoBlock = '';
        if ($logoUrl && filter_var($logoUrl, FILTER_VALIDATE_URL)) {
            $escapedLogo = htmlspecialchars($logoUrl, ENT_QUOTES, 'UTF-8');
            $logoBlock = <<<LOGO
<!-- wp:image {"width":"40px","height":"40px","sizeSlug":"full","style":{"border":{"radius":"4px"}}} -->
<figure class="wp-block-image size-full" style="width:40px;height:40px"><img src="{$escapedLogo}" alt="{$name} logo" style="border-radius:4px;width:40px;height:40px;object-fit:contain"/></figure>
<!-- /wp:image -->
LOGO;
        }

        return <<<HEADER
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--50)">
    <!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
    <div class="wp-block-group">
        {$logoBlock}
        <!-- wp:site-title {"level":0,"style":{"typography":{"fontWeight":"700"}}} /-->
    </div>
    <!-- /wp:group -->
    <!-- wp:navigation {"overlayMenu":"never","layout":{"type":"flex","justifyContent":"right"}} /-->
</div>
<!-- /wp:group -->
HEADER;
    }

    private function wrapTemplate(string $content, bool $skipHeader = false): string
    {
        $header = $skipHeader ? '' : "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n";
        return $header.
            $content."\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function defaultPageTemplate(): string
    {
        return "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n".
            "<!-- wp:group {\"tagName\":\"main\"} -->\n".
            "<main class=\"wp-block-group\">\n".
            "<!-- wp:group {\"layout\":{\"type\":\"constrained\"}} -->\n".
            "<div class=\"wp-block-group\">\n".
            "<!-- wp:post-content {\"layout\":{\"type\":\"constrained\"}} /-->\n".
            "</div>\n".
            "<!-- /wp:group -->\n".
            "</main>\n".
            "<!-- /wp:group -->\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function defaultSingleTemplate(): string
    {
        return "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n".
            "<!-- wp:group {\"tagName\":\"main\"} -->\n".
            "<main class=\"wp-block-group\">\n".
            "<!-- wp:group {\"layout\":{\"type\":\"constrained\"}} -->\n".
            "<div class=\"wp-block-group\">\n".
            "<!-- wp:post-title {\"level\":1} /-->\n".
            "<!-- wp:post-content {\"layout\":{\"type\":\"constrained\"}} /-->\n".
            "</div>\n".
            "<!-- /wp:group -->\n".
            "</main>\n".
            "<!-- /wp:group -->\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function default404Template(): string
    {
        return "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n".
            "<!-- wp:group {\"tagName\":\"main\"} -->\n".
            "<main class=\"wp-block-group\">\n".
            "<!-- wp:group {\"layout\":{\"type\":\"constrained\"}} -->\n".
            "<div class=\"wp-block-group\">\n".
            "<!-- wp:heading {\"level\":2} -->\n".
            "<h2 class=\"wp-block-heading\">Page not found</h2>\n".
            "<!-- /wp:heading -->\n".
            "<!-- wp:paragraph -->\n".
            "<p>The page you are looking for could not be found.</p>\n".
            "<!-- /wp:paragraph -->\n".
            "</div>\n".
            "<!-- /wp:group -->\n".
            "</main>\n".
            "<!-- /wp:group -->\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function defaultIndexTemplate(): string
    {
        return "<!-- wp:template-part {\"slug\":\"header\",\"tagName\":\"header\"} /-->\n\n".
            "<!-- wp:group {\"tagName\":\"main\"} -->\n".
            "<main class=\"wp-block-group\">\n".
            "<!-- wp:group {\"layout\":{\"type\":\"constrained\"}} -->\n".
            "<div class=\"wp-block-group\">\n".
            "<!-- wp:query {\"queryId\":1,\"query\":{\"perPage\":10,\"pages\":0,\"offset\":0,\"postType\":\"post\",\"order\":\"desc\",\"orderBy\":\"date\",\"author\":\"\",\"search\":\"\",\"exclude\":[],\"sticky\":\"\",\"inherit\":true}} -->\n".
            "<!-- wp:post-template -->\n".
            "<!-- wp:post-title {\"isLink\":true} /-->\n".
            "<!-- wp:post-excerpt /-->\n".
            "<!-- /wp:post-template -->\n".
            "<!-- wp:query-pagination -->\n".
            "<!-- wp:query-pagination-previous /-->\n".
            "<!-- wp:query-pagination-numbers /-->\n".
            "<!-- wp:query-pagination-next /-->\n".
            "<!-- /wp:query-pagination -->\n".
            "<!-- /wp:query -->\n".
            "</div>\n".
            "<!-- /wp:group -->\n".
            "</main>\n".
            "<!-- /wp:group -->\n\n".
            "<!-- wp:template-part {\"slug\":\"footer\",\"tagName\":\"footer\"} /-->\n";
    }

    private function zipTheme(string $themeDir, string $slug): string
    {
        $zipPath = sys_get_temp_dir()."/pp-themes/{$slug}.zip";
        $zip = new ZipArchive;

        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new RuntimeException('Unable to create zip archive.');
        }

        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($themeDir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($files as $file) {
            $filePath = $file->getRealPath();
            if (! $filePath) {
                continue;
            }

            $relativePath = substr($filePath, strlen($themeDir) + 1);

            if ($file->isDir()) {
                $zip->addEmptyDir($relativePath);
            } else {
                $zip->addFile($filePath, $relativePath);
            }
        }

        $zip->close();

        return $zipPath;
    }
}
