
import { PageContent } from '../types';

export const getUniversalHomeContent = (content?: PageContent) => {
    const title = content?.hero_title || 'Launch Your Vision';
    const sub = content?.hero_sub || 'A scalable, modern foundation generated by PressPilot.';
    const heroImage = content?.hero_image || 'https://placehold.co/1200x600/EEE/31343C.png?text=Hero+Image';

    return `
    <!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"layout":{"type":"constrained"}} -->
    <div class="wp-block-group alignfull" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0">
        
        <!-- wp:cover {"url":"${heroImage}","dimRatio":50,"overlayColor":"black","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|80","bottom":"var:preset|spacing|80"}}}} -->
        <div class="wp-block-cover alignfull has-black-background-color has-background-dim" style="padding-top:var(--wp--preset--spacing--80);padding-bottom:var(--wp--preset--spacing--80)">
            <span aria-hidden="true" class="wp-block-cover__background has-black-background-color has-background-dim-50"></span>
            <img class="wp-block-cover__image-background" src="${heroImage}" data-object-fit="cover"/>
            <div class="wp-block-cover__inner-container">
                <!-- wp:heading {"textAlign":"center","level":1,"fontSize":"x-large","style":{"typography":{"textTransform":"uppercase","letterSpacing":"2px"}}} -->
                <h1 class="wp-block-heading has-text-align-center has-x-large-font-size" style="text-transform:uppercase;letter-spacing:2px">${title}</h1>
                <!-- /wp:heading -->

                <!-- wp:paragraph {"align":"center","fontSize":"large"} -->
                <p class="has-text-align-center has-large-font-size">${sub}</p>
                <!-- /wp:paragraph -->

                <!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
                <div class="wp-block-buttons">
                    <!-- wp:button {"backgroundColor":"primary","textColor":"base"} -->
                    <div class="wp-block-button"><a class="wp-block-button__link has-base-color has-primary-background-color has-text-color has-background wp-element-button">Get Started</a></div>
                    <!-- /wp:button -->
                    <!-- wp:button {"className":"is-style-outline","style":{"color":{"text":"var:preset|color|white"},"border":{"color":"var:preset|color|white"}}} -->
                    <div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" style="color:var(--wp--preset--color--white);border-color:var(--wp--preset--color--white)">Learn More</a></div>
                    <!-- /wp:button -->
                </div>
                <!-- /wp:buttons -->
            </div>
        </div>
        <!-- /wp:cover -->

    </div>
    <!-- /wp:group -->

    <!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"4rem","bottom":"4rem"},"margin":{"top":"0","bottom":"0"}},"color":{"background":"var:preset|color|tertiary"}},"layout":{"type":"constrained"}} -->
    <div class="wp-block-group alignfull has-tertiary-background-color has-background" style="margin-top:0;margin-bottom:0;padding-top:4rem;padding-bottom:4rem">
        <!-- wp:columns {"align":"wide"} -->
        <div class="wp-block-columns alignwide">
            <!-- wp:column -->
            <div class="wp-block-column">
                <!-- wp:heading {"level":3} -->
                <h3 class="wp-block-heading">Speed</h3>
                <!-- /wp:heading -->
                <!-- wp:paragraph -->
                <p>Optimized for performance with zero bloat. Runs on native blocks.</p>
                <!-- /wp:paragraph -->
            </div>
            <!-- /wp:column -->
            <!-- wp:column -->
            <div class="wp-block-column">
                <!-- wp:heading {"level":3} -->
                <h3 class="wp-block-heading">Scale</h3>
                <!-- /wp:heading -->
                <!-- wp:paragraph -->
                <p>Built to grow with your business. Modular architecture.</p>
                <!-- /wp:paragraph -->
            </div>
            <!-- /wp:column -->
            <!-- wp:column -->
            <div class="wp-block-column">
                <!-- wp:heading {"level":3} -->
                <h3 class="wp-block-heading">Security</h3>
                <!-- /wp:heading -->
                <!-- wp:paragraph -->
                <p>Secure by default. No plugin dependencies or vulnerabilities.</p>
                <!-- /wp:paragraph -->
            </div>
            <!-- /wp:column -->
        </div>
        <!-- /wp:columns -->
    </div>
    <!-- /wp:group -->
    `;
};
