<?php
/**
 * Roma Pizza – core theme functions
 * Generated by PressPilot Theme Generator V1.1
 */

if ( ! function_exists( 'presspilot_roma_pizza_setup' ) ) :
	function presspilot_roma_pizza_setup() {
		add_theme_support( 'wp-block-styles' );
		add_theme_support( 'editor-styles' );
		add_theme_support( 'block-templates' );
		add_theme_support( 'responsive-embeds' );
		add_theme_support( 'title-tag' );
		add_theme_support( 'menus' );
		add_theme_support( 'post-thumbnails' );
		add_theme_support( 'automatic-feed-links' );
	}
endif;
add_action( 'after_setup_theme', 'presspilot_roma_pizza_setup' );

/**
 * Pattern category.
 */
function presspilot_roma_pizza_register_pattern_category() {
	register_block_pattern_category(
		'presspilot-roma-pizza',
		array(
			'label' => __( 'PressPilot / Roma Pizza', 'presspilot-roma-pizza' ),
		)
	);
}
add_action( 'init', 'presspilot_roma_pizza_register_pattern_category' );

/**
 * Register DB Prefix Endpoint.
 */
function presspilot_roma_pizza_register_db_prefix_endpoint() {
    register_rest_route( 'presspilot/v1', '/db-prefix', array(
        'methods'  => 'GET',
        'callback' => function() {
            global $wpdb;
            return array( 'table_prefix' => $wpdb->prefix );
        },
        'permission_callback' => '__return_true',
    ) );
}
add_action( 'rest_api_init', 'presspilot_roma_pizza_register_db_prefix_endpoint' );

/**
 * V1.1 Activation Logic
 * - Destructive Mode
 * - Content Generation
 * - Navigation Creation
 */
add_action( 'after_switch_theme', 'presspilot_roma_pizza_activate' );

function presspilot_roma_pizza_activate() {
    // Injected Config
    $destructive_mode = true;
    $site_title = 'Roma Pizza';

    // 1. Destructive mode: trash existing pages and wp_navigation posts.
    if ( $destructive_mode ) {
        $existing_pages = get_posts( array(
            'post_type'      => 'page',
            'posts_per_page' => -1,
            'post_status'    => 'any',
        ) );

        foreach ( $existing_pages as $page ) {
            wp_trash_post( $page->ID );
        }

        $existing_navs = get_posts( array(
            'post_type'      => 'wp_navigation',
            'posts_per_page' => -1,
            'post_status'    => 'any',
        ) );

        foreach ( $existing_navs as $nav ) {
            wp_trash_post( $nav->ID );
        }
    }

    // 2. Create pages from config.
    $pages_to_create = array(
        'home' => array( 'title' => 'Home', 'content' => 'Welcome to the V1.1 test site.' ),
        'about' => array( 'title' => 'About', 'content' => 'About this test theme.' ),
        'contact' => array( 'title' => 'Contact', 'content' => 'Contact us.' ),
    );

    $created_page_ids = array();

    foreach ( $pages_to_create as $slug => $data ) {
        // Check if page exists (if not destructive) to avoid duplicates
        $existing = get_page_by_path( $slug );
        if ( $existing ) {
            $created_page_ids[ $slug ] = $existing->ID;
            continue;
        }

        $page_id = wp_insert_post( array(
            'post_type'    => 'page',
            'post_title'   => $data['title'],
            'post_name'    => $slug,
            'post_content' => $data['content'],
            'post_status'  => 'publish',
        ) );

        if ( ! is_wp_error( $page_id ) ) {
            $created_page_ids[ $slug ] = $page_id;
        }
    }

    // 3. Set front page to "home" if it exists.
    if ( isset( $created_page_ids['home'] ) ) {
        update_option( 'show_on_front', 'page' );
        update_option( 'page_on_front', $created_page_ids['home'] );
    }

    // 4. ALWAYS: create a wp_navigation entity for the new pages.
    if ( ! empty( $created_page_ids ) ) {
        $nav_content = '<!-- wp:navigation -->';

        // Ensure order matches config, but force 'home' to be first if it exists
        $ordered_slugs = array(
            'home',
            'about',
            'contact',
        );

        foreach ( $ordered_slugs as $slug ) {
            if ( isset( $created_page_ids[ $slug ] ) ) {
                $id = $created_page_ids[ $slug ];
                $nav_content .= sprintf(
                    '<!-- wp:navigation-link {"label":"%s","type":"page","id":%d} /-->',
                    esc_html( get_the_title( $id ) ),
                    $id
                );
            }
        }

        $nav_content .= '<!-- /wp:navigation -->';

        $nav_id = wp_insert_post( array(
            'post_type'    => 'wp_navigation',
            'post_title'   => 'Main Navigation (AI)',
            'post_status'  => 'publish',
            'post_content' => $nav_content,
        ) );

        // 5. Inject Nav ID into Header (Runtime Override)
        if ( ! is_wp_error( $nav_id ) ) {
            $header_path = get_template_directory() . '/parts/header.html';
            if ( file_exists( $header_path ) ) {
                $header_content = file_get_contents( $header_path );
                
                // Inject ref attribute into the navigation block
                // We look for '<!-- wp:navigation {"ref":0' and replace it with '<!-- wp:navigation {"ref":ID'
                $header_content = str_replace(
                    '<!-- wp:navigation {"ref":0',
                    '<!-- wp:navigation {"ref":' . $nav_id,
                    $header_content
                );

                // Create a wp_template_part post to override the file-based header
                // Slug format: theme_slug//header
                $part_slug = 'presspilot-roma-pizza//header';
                
                // Check if it exists first
                $existing_part = get_page_by_path( $part_slug, OBJECT, 'wp_template_part' );
                
                $part_args = array(
                    'post_type'    => 'wp_template_part',
                    'post_title'   => 'Header',
                    'post_name'    => $part_slug,
                    'post_content' => $header_content,
                    'post_status'  => 'publish',
                    'tax_input'    => array(
                        'wp_theme'            => 'presspilot-roma-pizza',
                        'wp_template_part_area' => 'header',
                    ),
                );

                if ( $existing_part ) {
                    $part_args['ID'] = $existing_part->ID;
                    wp_update_post( $part_args );
                } else {
                    wp_insert_post( $part_args );
                }
            }
        }
    }

    // 5. Set Site Title
    update_option( 'blogname', $site_title );
}
