<?php
/**
 * PressPilot Gold Test helpers.
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Setup theme support to ensure Menus screen appears.
 */
function presspilot_gold_setup()
{
    // Registering a nav menu location often forces the "Menus" screen to appear in Appearance
    register_nav_menus(array(
        'primary' => 'Primary Menu',
    ));
    add_theme_support('menus');
}
add_action('after_setup_theme', 'presspilot_gold_setup');

/**
 * Robust content creation that runs on admin_init to ensure pages and menus exist.
 */
function presspilot_gold_ensure_content()
{
    // Define the current version of the content setup
    $setup_version = '1.0.17';

    // If we have already run the setup for this version, stop here.
    if (get_option('presspilot_gold_content_version') === $setup_version) {
        return;
    }

    // 0. Update Site Title
    update_option('blogname', 'PressPilot Gold Restaurant');

    // 1. Create Pages
    $pages_to_create = array(
        'Home' => 'home',
        'Menu' => 'menu',
        'About' => 'about',
        'Services' => 'services',
        'Blog' => 'blog',
        'Contact' => 'contact'
    );

    foreach ($pages_to_create as $page_title => $page_slug) {
        $existing_page = get_page_by_path($page_slug);

        // Only create if it doesn't exist (we won't restore from trash anymore to respect user deletion)
        if (!$existing_page) {
            $page_content = "<p>This is the <strong>$page_title</strong> page. Content generated by PressPilot Gold. Start building your layout here.</p>";

            switch ($page_slug) {
                case 'home':
                    // Use serialize_blocks() to let WordPress generate the valid markup
                    $blocks = array(
                        array(
                            'blockName' => 'core/group',
                            'attrs' => array(
                                'align' => 'full',
                                'backgroundColor' => 'secondary',
                                'layout' => array(
                                    'type' => 'constrained'
                                )
                            ),
                            'innerBlocks' => array(
                                array(
                                    'blockName' => 'core/spacer',
                                    'attrs' => array(
                                        'height' => '100px'
                                    )
                                ),
                                array(
                                    'blockName' => 'core/heading',
                                    'attrs' => array(
                                        'textAlign' => 'center',
                                        'textColor' => 'base',
                                        'level' => 1
                                    ),
                                    'innerContent' => array('Welcome to Our Restaurant')
                                ),
                                array(
                                    'blockName' => 'core/paragraph',
                                    'attrs' => array(
                                        'align' => 'center',
                                        'textColor' => 'base'
                                    ),
                                    'innerContent' => array('The finest dining experience, crafted just for you.')
                                ),
                                array(
                                    'blockName' => 'core/buttons',
                                    'attrs' => array(
                                        'layout' => array(
                                            'type' => 'flex',
                                            'justifyContent' => 'center'
                                        )
                                    ),
                                    'innerBlocks' => array(
                                        array(
                                            'blockName' => 'core/button',
                                            'attrs' => array(
                                                'className' => 'is-style-fill'
                                            ),
                                            'innerContent' => array('<a class="wp-block-button__link wp-element-button" href="/menu">View Menu</a>')
                                        )
                                    )
                                ),
                                array(
                                    'blockName' => 'core/spacer',
                                    'attrs' => array(
                                        'height' => '100px'
                                    )
                                )
                            )
                        )
                    );

                    $page_content = serialize_blocks($blocks);
                    break;
                case 'contact':
                    // Simple Contact section with form prompt
                    $page_content = '
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group">
<!-- wp:heading {"textAlign":"center"} -->
<h2 class="wp-block-heading has-text-align-center">Get in Touch</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">We would love to hear from you. Please use the form below to send us a message.</p>
<!-- /wp:paragraph -->
<!-- wp:shortcode -->
[contact-form-7 id="0000" title="Contact form 1"]
<!-- /wp:shortcode -->
</div>
<!-- /wp:group -->
';
                    break;
                default:
                    // Default content for all other pages
                    $page_content = "<p>This is the <strong>$page_title</strong> page. Content generated by PressPilot Gold. Start building your layout here.</p>";
                    break;
            }

            $page_data = array(
                'post_type' => 'page',
                'post_title' => $page_title,
                'post_name' => $page_slug,
                'post_content' => $page_content, // Use the new dynamic content
                'post_status' => 'publish',
                'post_author' => get_current_user_id(),
            );
            wp_insert_post($page_data);
        }
        // Removed the "restore from trash" logic so you can delete pages if you want.
    }

    // 2. Set Reading Settings
    $home_page = get_page_by_path('home');
    $blog_page = get_page_by_path('blog');

    if ($home_page && get_option('page_on_front') != $home_page->ID) {
        update_option('page_on_front', $home_page->ID);
        update_option('show_on_front', 'page');
    }
    if ($blog_page && get_option('page_for_posts') != $blog_page->ID) {
        update_option('page_for_posts', $blog_page->ID);
    }

    // 3. Create Classic Menu (Populates Appearance > Menus)
    $menu_name = 'Primary Menu';
    $menu_exists = wp_get_nav_menu_object($menu_name);

    if (!$menu_exists) {
        $menu_id = wp_create_nav_menu($menu_name);

        foreach ($pages_to_create as $page_title => $page_slug) {
            $page = get_page_by_path($page_slug);
            if ($page) {
                wp_update_nav_menu_item($menu_id, 0, array(
                    'menu-item-title' => $page_title,
                    'menu-item-object' => 'page',
                    'menu-item-object-id' => $page->ID,
                    'menu-item-type' => 'post_type',
                    'menu-item-status' => 'publish',
                ));
            }
        }

        // Assign to 'primary' location
        $locations = get_theme_mod('nav_menu_locations');
        $locations['primary'] = $menu_id;
        set_theme_mod('nav_menu_locations', $locations);
    }

    // Mark setup as done for this version
    update_option('presspilot_gold_content_version', $setup_version);
}
add_action('admin_init', 'presspilot_gold_ensure_content');
