<?php
/**
 * Roma Pizza – functions.php
 * Generated by PressPilot V4
 */

if ( ! function_exists( 'presspilot_roma_pizza_v4_setup' ) ) :
	function presspilot_roma_pizza_v4_setup() {
		add_theme_support( 'wp-block-styles' );
		add_theme_support( 'editor-styles' );
		add_theme_support( 'block-templates' );
		add_theme_support( 'responsive-embeds' );
		add_theme_support( 'title-tag' );
		add_theme_support( 'menus' );
		add_theme_support( 'post-thumbnails' );
	}
endif;
add_action( 'after_setup_theme', 'presspilot_roma_pizza_v4_setup' );

// V4 Activation: Create Pages & Navigation
add_action( 'after_switch_theme', 'presspilot_roma_pizza_v4_activate' );
function presspilot_roma_pizza_v4_activate() {
    $destructive = true;
    
    if ($destructive) {
        $pages = get_posts(['post_type'=>'page','numberposts'=>-1]);
        foreach($pages as $p) wp_trash_post($p->ID);
        $navs = get_posts(['post_type'=>'wp_navigation','numberposts'=>-1]);
        foreach($navs as $n) wp_trash_post($n->ID);
    }

    // Create Pages
    $pages_config = [
        'home' => ['title' => 'Home', 'content' => 'Welcome to our V4 site.'],
        'about' => ['title' => 'About Us', 'content' => 'We make the best pizza.'],
        'services' => ['title' => 'Services', 'content' => 'Dine-in, Takeout, Delivery.'],
        'contact' => ['title' => 'Contact', 'content' => 'Call us at 555-0199.'],
        'menu' => ['title' => 'Menu', 'content' => 'Pizza, Pasta, Salads.'],
    ];

    $created_ids = [];
    foreach ($pages_config as $slug => $data) {
        // V4: Wrap content in paragraph block automatically
        $content_block = '<!-- wp:paragraph --><p>' . $data['content'] . '</p><!-- /wp:paragraph -->';
        $id = wp_insert_post([
            'post_type' => 'page',
            'post_title' => $data['title'],
            'post_name' => $slug,
            'post_content' => $content_block,
            'post_status' => 'publish'
        ]);
        if (!is_wp_error($id)) $created_ids[$slug] = $id;
    }

    if (isset($created_ids['home'])) {
        update_option('show_on_front', 'page');
        update_option('page_on_front', $created_ids['home']);
    }

    // Create Navigation
    if (!empty($created_ids)) {
        $nav_content = '<!-- wp:navigation -->';
        foreach ($created_ids as $slug => $id) {
            $nav_content .= sprintf(
                '<!-- wp:navigation-link {"label":"%s","type":"page","id":%d} /-->',
                get_the_title($id), $id
            );
        }
        $nav_content .= '<!-- /wp:navigation -->';
        
        wp_insert_post([
            'post_type' => 'wp_navigation',
            'post_title' => 'Main Navigation',
            'post_content' => $nav_content,
            'post_status' => 'publish'
        ]);
    }
    
    update_option('blogname', 'Roma Pizza');
}
