<?php
/**
 * Title: Modern Home
 * Slug: presspilot-child/home-modern
 */
?>
<!-- wp:cover {"url":"https://s.w.org/images/core/5.3/MtBlanc1.jpg","dimRatio":50,"overlayColor":"black","align":"full"} -->
<div class="wp-block-cover alignfull"><span aria-hidden="true"
        class="wp-block-cover__background has-black-background-color has-background-dim-50 has-background-dim"></span><img
        class="wp-block-cover__image-background" src="https://s.w.org/images/core/5.3/MtBlanc1.jpg"
        data-object-fit="cover" />
    <div class="wp-block-cover__inner-container">
        <!-- wp:heading {"textAlign":"center","level":1,"textColor":"white"} -->
        <h1 class="has-text-align-center has-white-color has-text-color">Welcome to Your New Site</h1>
        <!-- /wp:heading -->

        <!-- wp:paragraph {"align":"center","textColor":"white","fontSize":"large"} -->
        <p class="has-text-align-center has-white-color has-text-color has-large-font-size">Generated by PressPilot
            Magic.</p>
        <!-- /wp:paragraph -->

        <!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
        <div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"vivid-green-cyan","textColor":"black"} -->
            <div class="wp-block-button"><a
                    class="wp-block-button__link has-black-color has-vivid-green-cyan-background-color has-text-color has-background">Order
                    Now</a></div>
            <!-- /wp:button -->
        </div>
        <!-- /wp:buttons -->
    </div>
</div>
<!-- /wp:cover -->